name = "Perishable"
description = "This mod is required by other mods that are using 'perishable.lua'."
author = "cr4shmaster"
version = "1.0.2"
forumthread = ""
api_version = 10
all_clients_require_mod = true
client_only_mod = false
dst_compatible = true
icon_atlas = "modicon.xml"
icon = "modicon.tex"
-- server_filter_tags = {""}
-- priority = 10.00